name: ssh
description: SSH and SFTP client for Flutter. Wraps iOS library NMSSH and Android library JSch.
version: 0.0.7
homepage: https://github.com/shaqian/flutter_ssh

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  lint: ^1.5.3
  meta: ^1.3.0
  uuid: ^3.0.4


flutter:
  plugin:
    platforms:
      android:
        package: sq.flutter.ssh
        pluginClass: SshPlugin
      ios:
        pluginClass: SshPlugin
